<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageTags>cCoder;Eventing;cCoder.Eventing;cCoder.Eventing.AzureServiceBus</PackageTags>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PrivateRepositoryUrl>https://github.com/ccoder-co-uk/ccoder.Eventing.git</PrivateRepositoryUrl>
		<ProjectUrl>https://github.com/ccoder-co-uk/ccoder.Eventing.git</ProjectUrl>
		<Description>cCoder.Eventing.AzureServiceBus</Description>

		<Authors>cCoder</Authors>
		<PackageId>cCoder.Eventing.AzureServiceBus</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	
</Project>
