<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageTags>cCoder;Eventing;cCoder.Eventing</PackageTags>
		<Version>2026.3.13.1755</Version>
		<AssemblyVersion>2026.3.13.1755</AssemblyVersion>
		<FileVersion>2026.3.13.1755</FileVersion>
		<InformationalVersion>2026.3.13.1755</InformationalVersion>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PrivateRepositoryUrl>https://github.com/ccoder-co-uk/ccoder.Eventing.git</PrivateRepositoryUrl>
		<ProjectUrl>https://github.com/ccoder-co-uk/ccoder.Eventing.git</ProjectUrl>
		<Description>cCoder.Eventing</Description>

		<Authors>cCoder</Authors>
		<PackageId>cCoder.Eventing</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="cCoder.CodeAnalysis" Version="2026.8.3.1611" />
	</ItemGroup>
	
</Project>
